### ISSUE TITLE
הלבנת ספריות - הבהרה

### ISSUE THREAD

**Issue by avielbr** [avielbr/theadrium#1]
מחכים לעדכון בנוגע לאופן העברת הספריות אל מחשב העבודה

**Comment by avielbr** [comment]
גכד

**Comment by OhadMar** [comment]
אלישע אמר שעד מחר אמור לקבל אישור. בשעות הבוקר אעדכן בתשובה שלו

**Comment by avielbr** [comment]
הספריות הותקנו
